# Generated by Django 5.2.1 on 2025-05-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_alter_ad_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads_images/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='barter.ad')),
            ],
        ),
    ]
